### ISSUE TITLE
Add grammar support for rate rules

### ISSUE THREAD

**Issue by mastevb** [sys-bio/vscode-antimony#45]
We urgently need to support Rate Rules in our grammar. Link to Antimony's documentation on Rate Rules: https://tellurium.readthedocs.io/en/latest/antimony.html#rate-rules. I think the only thing that differs rate rules from an assignment is just the `'` symbol following the name of the variable.
We would need a separate grammar for rate rules, and the parsing process should correctly recognize the assignee of the rate rule so we can display it on a hover.

**Comment by longxf21** [comment]
rate rules merged
