### ISSUE TITLE
Hover message for multiple annotations

### ISSUE THREAD

**Issue by mastevb** [sys-bio/vscode-antimony#59]
Hover message should correctly display URIs for variables that are annotated by multiple sources.

**Comment by joshNing** [comment]
Hi Steve, you want both the link and a short description for this right?

**Comment by mastevb** [comment]
@joshNing correct, that issue is being tracked here tho: https://github.com/sys-bio/vscode-antimony/issues/62

**Comment by mastevb** [comment]
> Hi Steve, you want both the link and a short description for this right?

@joshNing correct, that issue is being tracked here tho: https://github.com/sys-bio/vscode-antimony/issues/62
