### ISSUE TITLE
Visual indication for annotated variables

### ISSUE THREAD

**Issue by mastevb** [sys-bio/vscode-antimony#60]
Add a visual indication to show if a variable is annotated and/or a variable is not annotated.

Things to think about:
1. What kind of visual indication? We don't want the users to misread annotation indications and warnings/errors.
2. Show annotated variables, or unannotated variables?
3. Can users turn off the feature or switch between showing annotated variables, or unannotated variables?

**Comment by mastevb** [comment]
https://github.com/microsoft/vscode-discussions/discussions/46#discussioncomment-3051788

**Comment by evaliu2002** [comment]
Update: Completed implementing visual indication by presentation date with Dr. Sauro. Will now implement applying the visual indication to annotated variables and may proceed with an on/off switch afterward.

**Comment by evaliu2002** [comment]
Update: Completed obtaining list of annotated variables from back end. Will now implement decorator highlighting for the annotated variables.

**Comment by evaliu2002** [comment]
Update: Completed implementing decorator highlighting for annotated variables obtained from the backend. The feature is now finished. Will now implement on/off switch of the feature.

**Comment by evaliu2002** [comment]
Update: Completed right click for on/off switch of visual indications. Will now implement dynamic button title and might streamline switching on. Next is the extension setting of the switch.

**Comment by evaliu2002** [comment]
Update: Finished the extension setting for the switch. Will now implement unit tests for the feature.

**Comment by evaliu2002** [comment]
Update: Managed to figure out how to implement the dynamic button for the right-click menu and syncing for the user settings and right-click menu. Implemented two unit tests. Plan on implementing a few more before submitting a PR.

**Comment by evaliu2002** [comment]
Update: Implemented unit testing for button/setting syncing and also switching on and off of visual indications using the context menu

**Comment by evaliu2002** [comment]
As of VSCode 1.37.1 (2019-08-30), there is no way to write an automated test for decorations using the [decorations extensions API](https://code.visualstudio.com/api/references/vscode-api#TextEditorDecorationType).

There are automated tests of decorations in the vscode sources, particularly [modelDecorations.test.ts](https://github.com/microsoft/vscode/blob/master/src/vs/editor/test/common/model/modelDecorations.test.ts), but they use private APIs.

Microsoft has an example extension that uses decorators, [decorator-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/decorator-sample), but it has no tests.
